language: ruby
rvm:
- 2.2.0
notifications:
  webhooks:
    urls:
      secure: u0WLyr2NiAw/FrKh0VDVGF7AQezdu0f0Dp/hL55NSxFq0UOCIzjaIsUn8NkopVU3vDBngodjxvfcwbO0V0uZV13XAbpBPgt4+tEBkyxgYVEEW1+PjR74PSQasosJqh4i6GUOziuC0tyE6Hm/OEh2dPXkS5qNM4bhMdUpX83rKEHZybT0ACwCp+Uetodv35lON/XY7JAbaX68i8Lqm2ZLhI3AfIKiGiCH3lMbIxViNrPTQlFU20OTZQMNi12+rtkCKwrNpdpHsC76qFYTb+a1XmDN7Q+T06leTgczylsJbwWlyQo6sIIb9/nMT6p+DTkr8cc3lAXh2AWRNQFTiXsxjZBmdy9FLXtXTfGs7KyuTBmFdYY2enbAgFLTaod0rlKVnG+RSBc9sVNBjgfPWouY7s98f0sioNQD8WC+mVF5fwWwofCud+oPbVwMhgrI1s+US87AUr4MFdaxCQddGEDfLk5epMJnZUP5YJeUTL4Z0aChsF9qFatCqUHN8mT4b6iIEjRUz9ban4+C6zy1TQ4/ltePZuMHrIMZkfTKotsijh+eiUu/H2jkczdc3I94M5LjLM9H/85EPq3mdei8RLPaufFPcyVEu3haaDVvKwp6syotW532nmW4+iOt79HIOp0ZuswDAXJsS5ay+FuHPNtHREU90JlbPGFmSDwx80PQbwo=
